// <auto-generated />
using System;
using KalenderMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KalenderMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241029215659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("KalenderMVC.Models.Kasutajad", b =>
                {
                    b.Property<int>("KasutajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kasutajanimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Loodud")
                        .HasColumnType("TEXT");

                    b.Property<string>("Salasona")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KasutajaId");

                    b.ToTable("Kasutajad");
                });

            modelBuilder.Entity("KalenderMVC.Models.Meeldetuletus", b =>
                {
                    b.Property<int>("MeeldetuletusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MeeldetuletuseAeg")
                        .HasColumnType("TEXT");

                    b.Property<int>("SondmusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MeeldetuletusId");

                    b.HasIndex("SondmusId");

                    b.ToTable("Meeldetuletused");
                });

            modelBuilder.Entity("KalenderMVC.Models.Sondmus", b =>
                {
                    b.Property<int>("SondmusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AlgusAeg")
                        .HasColumnType("TEXT");

                    b.Property<int>("KasutajaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kirjeldus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoppAeg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pealkiri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SondmusId");

                    b.HasIndex("KasutajaId");

                    b.ToTable("Sondmused");
                });

            modelBuilder.Entity("KalenderMVC.Models.Meeldetuletus", b =>
                {
                    b.HasOne("KalenderMVC.Models.Sondmus", "Sondmus")
                        .WithMany()
                        .HasForeignKey("SondmusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sondmus");
                });

            modelBuilder.Entity("KalenderMVC.Models.Sondmus", b =>
                {
                    b.HasOne("KalenderMVC.Models.Kasutajad", "Kasutaja")
                        .WithMany()
                        .HasForeignKey("KasutajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kasutaja");
                });
#pragma warning restore 612, 618
        }
    }
}
